sudo: false
language: haxe

os:
  - linux

haxe:
  - "3.2.1"
  - development

before_install:
    - git clone https://github.com/haxeui/haxeui-core.git --depth=1
    - haxelib dev haxeui-core haxeui-core


install:
    - haxelib install hscript
    - haxelib install pixijs
    # - haxelib dev haxeui-pixijs $TRAVIS_BUILD_DIR

script:
    - haxe build.hxml